### PR TITLE
Latest ReactiveCocoa (4.2.2) support.

### PR DESCRIPTION
**Pull request by werediver**
podspec: version patch number bump and explicit version requirements for dependencies.
Podfile: cleanup, fixes, and compatibility with CocoaPods 1.0.

P.S. Consider removing `Example/Pods` directory from under version control.

### CODE REVIEW

**Comment by wattson12** [comment]
Thanks for this. Good point about the pods, I'll remove them as well

**Comment by werediver** [comment]
It would be great to have this new version available as CocoaPod. Are you going to publish it in the near time?

**Comment by wattson12** [comment]
validating the podspec before pushing as we speak :)

**Comment by wattson12** [comment]
Should be pushed now. 

I don't use ReactiveCocoa so don't follow it's releases, if you would like access to the repo / pod I'm happy to add you so this can be quicker for you next time?

**Comment by werediver** [comment]
I confirm that the new version is now available ( https://cocoapods.org/?q=moya-argo ).

Now I work on a (closed source) project where ReactiveCocoa, Moya, and Argo are in use. It may be helpful to have access to this repo / pod for maintenance purposes. If you don't mind such cooperation, I'm in.

**Comment by wattson12** [comment]
The more the better :) Invite sent, once thats done if you setup a cocoapods session and send me the email you used i can give you access: https://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Pull request merged**
