### PR TITLE
support iOS 11

### PR DESCRIPTION
**Pull request by kingiol**

### CODE REVIEW

**Comment by wattson12** [comment]
Looks good, thanks for this 👍 

I'll try to find time next week to clean up the warnings / let Xcode do the swift 4 migration

**Comment by wattson12** [comment]
I've bumped the version number but I'm travelling today so don't have the connection to push a new version to pods. Pointing to `master` or `2.1.0` tag should work in the meantime, and I'll push a new version when I can

If you'd like permission to push the version yourself just drop me an email, and I'll add you as a contributor

**Comment by kingiol** [comment]
kingxiaokang@gmail.com
I use this email to push podspec file to cocoapods

**Comment by wattson12** [comment]
added

**Comment by kingiol** [comment]
Done

**Pull request merged**
