### PR TITLE
support Moya 9.0.0

### PR DESCRIPTION
**Pull request by kingiol**

### CODE REVIEW

**Comment by wattson12** [comment]
This looks good to me, would be good to fix the CI but i don't think thats related to this so i'll make a new ticket

Can you bump the podspec version number? typically we've been using major version numbers if moya would be a breaking change so this might be version 3?

**Comment by wattson12** [comment]
Awesome, thanks a lot, happy to merge 🎉

**Comment by kingiol** [comment]
with update podspec, you will tag 3.0.0

**Comment by wattson12** [comment]
Yep, just pushing the new pod version now

**Pull request merged**
