### PR TITLE
support Moya 10.0.0 & rename ReactiveCoaoa to ReactiveSwift

### PR DESCRIPTION
**Pull request by kingiol**

### CODE REVIEW

**Comment by wattson12** [comment]
looks good, looks like CI failed because of cartography versions. I'll make a new issue to drop that as a dependency, no real reason to have it other than I was using it at the time I made the demo project

**Review by wattson12 — CHANGES_REQUESTED** [review]
Only thing missing i think is a version bump for this pod itself

**Comment by kingiol** [comment]
I think the CI failed because of Example/Podfile pod 'Moya-Argo/ReactiveCocoa', :path => "../"

you can try to change the line to pod 'Moya-Argo/ReactiveSwift', :path => "../"

**Comment by wattson12** [comment]
Thanks, will take a look. I added https://github.com/wattson12/Moya-Argo/issues/17 to track it

**Comment by kingiol** [comment]
@wattson12 Now CI Success. Please merge PRs.

**Comment by wattson12** [comment]
@kingiol CI looks good, thanks 👍 but I don't see a change to the pod version?

**Comment by kingiol** [comment]
@wattson12 You can make a new tag for the pod version, then push your podspec to cocoapods

**Comment by wattson12** [comment]
Should be pushed now, thanks again

**Pull request merged**
