### PR TITLE
Migrate to Swift 3

### PR DESCRIPTION
**Pull request by talesp**
Update podspec file to Moya, Argo and ReactiveSwift (not ReactiveCocoa
anymore) supporting Swift 3.

All tests passing.

Migration done with Xcode 8.2 beta 2 and CocoaPods 1.2 beta 1. Minimum deployment target updated to iOS 9.0 following requisite for Moya 8.0

### CODE REVIEW

**Comment by werediver** [comment]
I'd prefer not to use beta-versions of development tools as well as beta-versions of other frameworks here. Are there strong reasons to do so?

Also, I haven't been able to build the project using Xcode 8.1 (stable), but maybe it's a local glitch (didn't spend much time investigating).

Meanwhile, the PR looks promising, so thank you for your effort!

**Comment by wattson12** [comment]
Moya's master version seems to be still in beta so I think the beta requirement is OK, but I would suggest marking the version of this podspec as beta to make it clear there are beta dependencies? (or alpha since thats the state of ReactiveSwift I think? I use RxSwift so not sure on that one)

And forgot to say, thanks a lot for the work here, very much appreciated. I hope the migration wasn't too painful for you

**Comment by werediver** [comment]
Thanks for your notes on alpha and beta statuses of the dependencies, @wattson12.

It seems reasonable to me to mark this Moya-Argo version as *alpha* as the most unstable dependency is.

And I think it's important to make sure it's compatible with the stable Xcode 8.1.

**Comment by wattson12** [comment]
👍 to both points

**Comment by talesp** [comment]
I agree in marking this version as an alpha one. I updated to 1.2.0, but makes really sense. What do you think about `1.2.0-alpha.1`?

@werediver as I said, I did the migration with Xcode 8.2 beta 2. Maybe this is the problem. I'll fix it

**Comment by wattson12** [comment]
`-alpha.1` makes sense to me, this is a breaking change though so maybe it should be `2.0.0-alpha.1`?

**Comment by werediver** [comment]
> this is a breaking change though so maybe it should be `2.0.0-alpha.1`?

@wattson12 Agree, Swift 2.2 to Swift 3.0 is a breaking change and deserves the major version number bump.

> @werediver as I said, I did the migration with Xcode 8.2 beta 2. Maybe this is the problem. I'll fix it

@talesp It would be great if you can check the project on Xcode 8.1. I don't thing the migration done by a newer version is a problem (I hope it isn't).

**Comment by BenEmdon** [comment]
Any timeline on when this will merge or when a Swift 3 version will come?

**Comment by wattson12** [comment]
Sorry for the delay, because this branch hasn't been touched in a while and 8.2 was still in beta I started a new branch which is now merged to master. 

Marked as 2.0.0 since the change to swift 3 is breaking (and dependencies all had a major version bump)

Let me know if there are any issues. Thanks!

**Pull request closed without merging**
