### PR TITLE
Added support for Swift 3.0

### PR DESCRIPTION
**Pull request by Guziq**

### CODE REVIEW

**Comment by werediver** [comment]
It breaks compatibility with Swift 2.2 projects, doesn't it? (sorry, can't check right now)
If so, we need major version number bump.

Also the dependencies should be inspected and updated if necessary.

**Comment by Guziq** [comment]
Yes, Swift 3.0 is not backward compatible with 2.x

**Comment by wattson12** [comment]
Yep we'd need to update the podspec to get Moya v8 which should grab the swift 3 compatible versions of `Moya/ReactiveCocoa` and `Moya/RxSwift`

**Comment by BenEmdon** [comment]
I suppose this can close because Swift 3 support just merged to master?

**Comment by wattson12** [comment]
yep, 3.0 support should be good to go now

**Pull request closed without merging**
